---
galaxy_info:
  role_name: mariadb
  author: Arun
  description: Install/enable MariaDB and create Nextcloud DB/user.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "10"

dependencies: []
