---
galaxy_info:
  role_name: nextcloud
  author: Arun
  description: Deploy Nextcloud into /var/www/html/nextcloud with DB and S3 primary storage configuration.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "10"

dependencies: []
